<?php $q = $_GET; unset($q['r'], $q['page']); ?>
<div class="page-head"><div><div class="crumbs"><a href="<?= url('/admin/reports') ?>">گزارش‌ها</a></div><h1>گزارش پیشرفت و عملکرد</h1></div><?php if (can('reports.export')): ?><a class="btn btn-outline" href="<?= url('/admin/reports/progress', $q + ['export' => 1]) ?>"><?= icon('file-spreadsheet') ?> Excel</a><?php endif; ?></div>
<form class="card filters" method="get" action="<?= url('/admin/reports/progress') ?>">
    <div class="field"><label>وضعیت</label><select name="state"><option value="">همه</option><option value="overdue"<?= selected('overdue', $_GET['state'] ?? '') ?>>عقب‌افتاده / منقضی</option><?php foreach (['not_started', 'in_progress', 'completed', 'needs_retake', 'failed', 'locked', 'expired'] as $s): ?><option value="<?= $s ?>"<?= selected($s, $_GET['state'] ?? '') ?>><?= e(label('status', $s)) ?></option><?php endforeach; ?></select></div>
    <div class="field grow"><label>دوره</label><select name="course"><option value="">همه</option><?php foreach ($courses as $k => $t): ?><option value="<?= (int)$k ?>"<?= selected($k, $_GET['course'] ?? '') ?>><?= e($t) ?></option><?php endforeach; ?></select></div>
    <div class="field"><label>گروه</label><select name="group"><option value="">همه</option><?php foreach ($groups as $k => $t): ?><option value="<?= (int)$k ?>"<?= selected($k, $_GET['group'] ?? '') ?>><?= e($t) ?></option><?php endforeach; ?></select></div>
    <div class="field"><label>نوع آموزش</label><select name="type"><option value="">همه</option><?php foreach (App\Core\Labels::TRAINING_TYPE as $k => $t): ?><option value="<?= $k ?>"<?= selected($k, $_GET['type'] ?? '') ?>><?= e($t) ?></option><?php endforeach; ?></select></div>
    <button class="btn btn-primary"><?= icon('filter') ?></button>
</form>
<div class="card flush"><div class="table-wrap"><table class="table"><thead><tr><th>فراگیر</th><th>دوره</th><th>نوع</th><th>پیشرفت</th><th>نمره</th><th>وضعیت</th><th>مهلت</th><th>آخرین فعالیت</th></tr></thead><tbody>
<?php foreach ($page['rows'] as $e): $late = $e['due_at'] && $e['due_at'] < now() && $e['status'] !== 'completed'; ?><tr><td><a href="<?= url('/admin/reports/user/' . $e['user_id']) ?>"><?= person_name($e, 'user_id') ?></a></td><td class="small"><?= e($e['title']) ?></td><td><span class="badge badge-gray"><?= e(label('training_type', $e['training_type'])) ?></span></td>
<td style="min-width:130px"><div class="flex"><div class="grow"><?= progress_bar((float)$e['progress_pct']) ?></div><span class="small"><?= fa((int)$e['progress_pct']) ?>٪</span></div></td><td class="num"><?= $e['score'] !== null ? fa((float)$e['score']) : '—' ?></td><td><?= status_badge($e['status']) ?></td><td class="num small" style="<?= $late ? 'color:var(--danger);font-weight:700' : '' ?>"><?= $e['due_at'] ? jdate($e['due_at']) : '—' ?></td><td class="small"><?= time_ago($e['last_activity_at']) ?></td></tr><?php endforeach; ?>
<?php if (!$page['rows']): ?><tr><td colspan="8"><div class="empty"><?= icon('gauge') ?><div>موردی یافت نشد</div></div></td></tr><?php endif; ?>
</tbody></table></div></div>
<?= paginate_links($page) ?>
